//! Build script. Declares the app's IPC commands so each one needs an explicit permission (least privilege, granted in
//! `capabilities/default.json`) and checks that the bundled PDFium has been fetched.

use std::path::Path;

/// A build without the `automation` feature deletes the permission files an earlier acceptance build left in this tree, so a release
/// build can never pick them up (ADR-131). The files are ignored by git and regenerated by the next acceptance build.
fn remove_stale_automation_permissions() {
    let Ok(entries) = std::fs::read_dir("permissions/autogenerated") else {
        return;
    };
    for entry in entries.flatten() {
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name.starts_with("automation_") && name.ends_with(".toml") {
            let _ = std::fs::remove_file(entry.path());
        }
    }
}

fn main() {
    println!("cargo:rerun-if-changed=pdfium");
    if !Path::new("pdfium").is_dir() {
        panic!(
            "PDFium is not fetched yet. Run `npm run fetch-pdfium` (scripts/fetch-pdfium.sh) from the repository root."
        );
    }

    let mut commands = vec![
        "open_document_dialog",
        "open_welcome_document",
        "unlock_document",
        "list_recents",
        "remove_recent",
        "open_recent",
        "restore_recent",
        "set_recent_starred",
        "reveal_recent",
        "locate_recent",
        "get_recent_thumbnail",
        "set_menu_state",
        "render_page",
        "set_viewport",
        "get_pages",
        "get_outline",
        "get_text_layer",
        "text_edit_probe",
        "text_edit_lines",
        "text_edit_preview",
        "search",
        "cancel_search",
        "get_page_links",
        "open_link",
        "smart_links",
        "ocr_capabilities",
        "ocr_classify_pages",
        "ocr_start",
        "ocr_cancel",
        "ocr_open_language_settings",
        "list_annotations",
        "list_document_annotations",
        "get_annotation_quote",
        "import_warnings",
        "create_citations",
        "list_citations",
        "get_bibliography",
        "get_header_footer",
        "resolve_header_footer",
        "detect_header_footer",
        "save_citation_list",
        "list_signing_identities",
        "create_signing_identity",
        "pick_identity_file",
        "import_signing_identity",
        "discard_identity_import",
        "delete_signing_identity",
        "export_signing_certificate",
        "sign_document",
        "save_unsigned_copy",
        "validate_signatures",
        "open_signed_revision",
        "set_signer_trust",
        "list_trusted_signers",
        "remove_trusted_signer",
        "apply_command",
        "get_form_fields",
        "pick_pdf_sources",
        "release_source",
        "undo",
        "redo",
        "get_history",
        "save_document",
        "save_document_as",
        "extract_pages",
        "split_document",
        "merge_documents",
        "compress_document",
        "flatten_document",
        "estimate_compression",
        "cancel_job",
        "close_document",
        "app_ready",
        "get_settings",
        "update_settings",
        "subscribe_menu",
        "subscribe_app",
        "clear_signature_library",
        "get_library_signature",
        "delete_signature",
        "rename_signature",
        "save_library_signature",
        "list_signatures",
        "use_signature",
        "get_signature_preview",
        "discard_signature_draft",
        "save_draft_signature",
        "import_signature_image",
        "create_typed_signature",
        "create_drawn_signature",
        "insert_image_dialog",
        "get_asset_preview",
        "apply_redactions",
        "get_protection",
        "stage_protection",
        "stage_unprotection",
        "get_metadata",
        "export_images",
        "resolve_export_conflicts",
        "images_to_pdf",
        "release_image_batch",
        "pick_images",
        "list_image_batch",
        "get_image_batch_preview",
        "export_pdf",
        "export_comments",
        "export_text_pdf",
        "prepare_print",
        "get_print_page",
        "open_print_dialog",
        "release_print",
        "list_recoveries",
        "restore_recovery",
        "discard_recovery",
        "discard_all_recoveries",
        "undo_discard_recovery",
        "check_for_update",
        "download_update",
        "install_update_on_quit",
        "skip_update_version",
        "updater_configured",
        "open_default_apps_settings",
    ];
    // ADR-131: the acceptance build only; the permissions exist only there and only its inline capability grants them.
    if std::env::var_os("CARGO_FEATURE_AUTOMATION").is_some() {
        commands.extend(["automation_queue_dialog", "automation_state"]);
    } else {
        remove_stale_automation_permissions();
    }
    let manifest = tauri_build::AppManifest::new().commands(Box::leak(commands.into_boxed_slice()));
    if let Err(error) =
        tauri_build::try_build(tauri_build::Attributes::new().app_manifest(manifest))
    {
        panic!("tauri-build failed: {error:#}");
    }
}
