import { call } from './call';
import { toAppError } from './errors';
import { newChannel, parseJobId, type JobEvent, type JobId } from './jobs';
import type { PageSelection } from './pageSelection';

/*
 * PDF to PNG/JPEG (docs/ARCHITECTURE.md section 5, "Convert and output", ADR-049; commands/export_images.rs). The folder comes from
 * Rust's dialog after Go; nothing here holds a path.
 */

export interface ImageExportOptions {
  pages: PageSelection;
  /** 36..=600. */
  dpi: number;
  format: 'png' | 'jpeg';
  /** 1..=100, ignored for png. */
  jpegQuality: number;
  annotations: boolean;
}

/** What `export_images` answers: a job started, the folder dialog was cancelled, or files exist already and the user decides. */
export type ExportStart =
  | { type: 'started'; jobId: JobId }
  | { type: 'cancelled' }
  | {
      type: 'conflicts';
      ticket: number;
      count: number;
      /** At most 5 file names, generated by Rust (never a path). */
      names: string[];
    };

export type ConflictChoice = 'replace' | 'keepBoth' | 'cancel';

const MAX_NAMES = 5;
const whole = (value: unknown): value is number =>
  typeof value === 'number' && Number.isInteger(value) && value >= 0 && value <= Number.MAX_SAFE_INTEGER;

/** An `ExportStart` from an answer; `null` if it is not one. */
export function parseExportStart(value: unknown): ExportStart | null {
  if (typeof value !== 'object' || value === null) return null;
  const { type, jobId, ticket, count, names } = value as Record<string, unknown>;
  if (type === 'cancelled') return { type };
  if (type === 'started') return whole(jobId) ? { type, jobId } : null;
  if (type === 'conflicts') {
    if (!whole(ticket) || !whole(count) || !Array.isArray(names) || names.length > MAX_NAMES) return null;
    if (!names.every((name): name is string => typeof name === 'string')) return null;
    return { type, ticket, count, names: [...names] };
  }
  return null;
}

/**
 * Validates, shows Rust's folder dialog and starts the job; progress and the result come on `onEvent` (phases `render` and `encode`,
 * `done.outputs` files, `done.warnings` may hold `dpiLowered`). Rejects with `limit_exceeded` `exportPixels` (`params.page`),
 * `invalid_argument` `pageSelection` or `read_only` `permission`.
 */
export async function exportImages(
  docId: number,
  opts: ImageExportOptions,
  onEvent: (event: JobEvent) => void,
): Promise<ExportStart> {
  const answer = parseExportStart(await call<unknown>('export_images', { docId, opts, onEvent: newChannel(onEvent) }));
  if (answer === null) throw toAppError(null);
  return answer;
}

/** Carries out the choice for the held ticket. `null`: cancelled, or the ticket expired. */
export async function resolveExportConflicts(
  ticket: number,
  choice: ConflictChoice,
  onEvent: (event: JobEvent) => void,
): Promise<JobId | null> {
  return parseJobId(await call<unknown>('resolve_export_conflicts', { ticket, choice, onEvent: newChannel(onEvent) }));
}
