// owned by package A
//! PDF to PNG/JPEG (ADR-049 §2): options, the folder dialog, conflicts and the render job.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use tauri::WebviewWindow;

use crate::commands::jobs::{EventSink, JobId};
use crate::commands::AppState;
use crate::documents::DocumentId;
use crate::error::AppError;
use crate::model::ranges::PageSelection;

/// The file format of an image export.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ImageFormat {
    Png,
    Jpeg,
}

/// What `export_images` takes: pages, dpi 36..=600, format, JPEG quality 1..=100 (ignored for PNG), annotations on or off.
#[derive(Debug, Clone, PartialEq, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ImageExportOptions {
    pub pages: PageSelection,
    pub dpi: f32,
    pub format: ImageFormat,
    pub jpeg_quality: u8,
    pub annotations: bool,
}

/// How `export_images` answered: a job started, the folder dialog was cancelled, or names clash and the user decides
/// (`resolve_export_conflicts`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum ExportStart {
    Started {
        job_id: JobId,
    },
    Cancelled,
    /// Up to five names, generated by Rust.
    Conflicts {
        ticket: u32,
        count: u32,
        names: Vec<String>,
    },
}

/// What the user chose for files that exist already.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ConflictChoice {
    Replace,
    KeepBoth,
    Cancel,
}

/// Validates, asks for the folder and starts the job. Stub (package A): `not_yet`.
pub fn start(
    _state: &AppState,
    _window: &WebviewWindow,
    _doc: DocumentId,
    _opts: &ImageExportOptions,
    _sink: Arc<dyn EventSink>,
) -> Result<ExportStart, AppError> {
    Err(AppError::not_yet())
}

/// Carries out the choice for the held ticket; `None` for `cancel` or an expired ticket. Stub (package A): `not_yet`.
pub fn resolve(
    _state: &AppState,
    _ticket: u32,
    _choice: ConflictChoice,
    _sink: Arc<dyn EventSink>,
) -> Result<Option<JobId>, AppError> {
    Err(AppError::not_yet())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn options_parse_from_the_wire_and_answers_have_their_shape() {
        let opts: ImageExportOptions = serde_json::from_str(
            r#"{"pages":{"type":"ranges","text":"1-3"},"dpi":150,"format":"jpeg","jpegQuality":85,"annotations":true}"#,
        )
        .unwrap();
        assert_eq!(opts.format, ImageFormat::Jpeg);
        assert!(serde_json::from_str::<ImageExportOptions>(
            r#"{"pages":{"type":"all"},"dpi":150,"format":"gif","jpegQuality":85,"annotations":true}"#
        )
        .is_err());
        assert_eq!(
            serde_json::from_str::<ConflictChoice>(r#""keepBoth""#).unwrap(),
            ConflictChoice::KeepBoth
        );
        let value = |start: &ExportStart| serde_json::to_value(start).unwrap();
        assert_eq!(
            value(&ExportStart::Cancelled),
            serde_json::json!({"type": "cancelled"})
        );
        assert_eq!(
            value(&ExportStart::Conflicts {
                ticket: 2,
                count: 3,
                names: vec!["a.png".to_owned()]
            }),
            serde_json::json!({"type": "conflicts", "ticket": 2, "count": 3, "names": ["a.png"]})
        );
    }
}
